name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-msvc
            os: windows-2022
          - name: macos-appleclang
            os: macos-15
          - name: linux-gcc
            os: ubuntu-24.04
            cxx: g++-14
          - name: linux-clang
            os: ubuntu-24.04
            cxx: clang++-18
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
        env:
          CXX: ${{ matrix.cxx }}
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
